// Auto-generated by scripts/fetch-stock-photos.mjs — do not hand-edit.
// Curated South Indian portrait & wedding photos from Unsplash (free license,
// hotlink-safe CDN URLs). Regenerate with:
//   UNSPLASH_ACCESS_KEY=... node scripts/fetch-stock-photos.mjs

export interface StockPhoto {
  id: string;
  regular: string;
  small: string;
  alt: string;
}

export const avatarPhotos: { men: StockPhoto[]; women: StockPhoto[] } = {
  "men": [
    {
      "id": "tBb9r_x5SHE",
      "regular": "https://images.unsplash.com/photo-1647598378229-a0ec16456b1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1647598378229-a0ec16456b1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a black and white photo of a man with a scarf around his neck"
    },
    {
      "id": "96hIuXp5Bcg",
      "regular": "https://images.unsplash.com/photo-1647598378432-1aa8fa34f37f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1647598378432-1aa8fa34f37f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a black and white photo of a man smiling"
    },
    {
      "id": "-F3CZOe9a2M",
      "regular": "https://images.unsplash.com/photo-1577976085628-ea1297582be9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1577976085628-ea1297582be9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "greyscale photography of man"
    },
    {
      "id": "YnFgprdyzQ4",
      "regular": "https://images.unsplash.com/photo-1751660769801-43c0b1161c85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1751660769801-43c0b1161c85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A person smiles warmly at the camera."
    },
    {
      "id": "KfEQ01oMnjM",
      "regular": "https://images.unsplash.com/photo-1651908637597-679fe20cdc97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1651908637597-679fe20cdc97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a person with the hands together"
    },
    {
      "id": "iiyMYLnWo1g",
      "regular": "https://images.unsplash.com/photo-1661112952418-84a766daacf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1661112952418-84a766daacf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a man with a beard"
    },
    {
      "id": "xLKgGxKM_ZE",
      "regular": "https://images.unsplash.com/photo-1526785654655-e01ea2b6e2cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1526785654655-e01ea2b6e2cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "man wearing body piercing lot"
    },
    {
      "id": "vqqmxySckuU",
      "regular": "https://images.unsplash.com/photo-1778658585674-d29c1569be26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1778658585674-d29c1569be26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "Elderly man with a mustache smoking a cigarette."
    },
    {
      "id": "rViBhQwAZKU",
      "regular": "https://images.unsplash.com/photo-1612628418737-a2a0d159bec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1612628418737-a2a0d159bec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMG1hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "man in black crew neck shirt"
    },
    {
      "id": "oVfjpXKPsvk",
      "regular": "https://images.unsplash.com/photo-1571429682160-bbf6f518e955?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1571429682160-bbf6f518e955?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "shallow focus photo of man in white long-sleeved shirt"
    },
    {
      "id": "IuWuNxdZDoQ",
      "regular": "https://images.unsplash.com/photo-1699607178193-7b87beae167f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1699607178193-7b87beae167f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a man with a beard standing in front of a wall"
    },
    {
      "id": "UazoQTbhrjM",
      "regular": "https://images.unsplash.com/photo-1605857840732-188f2f08cb31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1605857840732-188f2f08cb31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "man in black framed eyeglasses and black crew neck shirt"
    },
    {
      "id": "M3_aLTYxn4U",
      "regular": "https://images.unsplash.com/photo-1774437557684-2439c4a51327?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1774437557684-2439c4a51327?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "An elderly man with glasses and a beard."
    },
    {
      "id": "nMFJXVuQVOo",
      "regular": "https://images.unsplash.com/photo-1763395262634-99f7ae8704b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1763395262634-99f7ae8704b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "Man wearing sunglasses and a colorful shirt."
    },
    {
      "id": "gqiTvcBF-zs",
      "regular": "https://images.unsplash.com/photo-1735882982157-76428cc107e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1735882982157-76428cc107e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjBtYW4lMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A black and white photo of a man smoking a cigarette"
    }
  ],
  "women": [
    {
      "id": "5lUBET_HypI",
      "regular": "https://images.unsplash.com/photo-1772037848780-f4c456155b90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1772037848780-f4c456155b90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A woman in a green sari smiles outdoors"
    },
    {
      "id": "DdLL2OZsorM",
      "regular": "https://images.unsplash.com/photo-1626872580370-7a7abca681d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1626872580370-7a7abca681d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "woman in blue v neck shirt"
    },
    {
      "id": "-2uwItf15Bg",
      "regular": "https://images.unsplash.com/photo-1732888878731-7e52999af144?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1732888878731-7e52999af144?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A black and white photo of a woman"
    },
    {
      "id": "G0LILicjiUY",
      "regular": "https://images.unsplash.com/photo-1584093493003-900ade863b6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1584093493003-900ade863b6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "woman in purple and white dress leaning on brown wooden post"
    },
    {
      "id": "ikbFZcZDjno",
      "regular": "https://images.unsplash.com/photo-1749017818421-aadb344f32d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1749017818421-aadb344f32d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A woman gazes into the distance amidst trees."
    },
    {
      "id": "EAq7Cs7-0Fs",
      "regular": "https://images.unsplash.com/photo-1597897569217-b1e3ebf98c6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1597897569217-b1e3ebf98c6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "woman in yellow and red sari dress"
    },
    {
      "id": "irzdpArDxvc",
      "regular": "https://images.unsplash.com/photo-1547496522-697de08bfa58?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1547496522-697de08bfa58?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "woman wearing maroon and multicolored floral top"
    },
    {
      "id": "EgA5r70B67U",
      "regular": "https://images.unsplash.com/photo-1783067642151-72350bb9f6d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1783067642151-72350bb9f6d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "Elderly woman in red sari sitting at an outdoor market."
    },
    {
      "id": "u_JBECP7kKE",
      "regular": "https://images.unsplash.com/photo-1634108783851-f97f86257d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1634108783851-f97f86257d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMHdvbWFuJTIwcG9ydHJhaXR8ZW58MHwyfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a black and white photo of a woman wearing a bandana"
    },
    {
      "id": "YJr9EDEIsN8",
      "regular": "https://images.unsplash.com/photo-1736995473274-58e20982273e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1736995473274-58e20982273e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A woman is looking up at the sky"
    },
    {
      "id": "YluWpboXXrY",
      "regular": "https://images.unsplash.com/photo-1716504189135-23f067f0db1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1716504189135-23f067f0db1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a close up of a person with a cell phone"
    },
    {
      "id": "ABkHG5_sENs",
      "regular": "https://images.unsplash.com/photo-1645106281520-35aa85ceafc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1645106281520-35aa85ceafc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "a black and white photo of a woman"
    },
    {
      "id": "WMCB9UZRnUg",
      "regular": "https://images.unsplash.com/photo-1581488613476-ea9bcf51ccf7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1581488613476-ea9bcf51ccf7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "man in red hijab sitting beside green wooden wall"
    },
    {
      "id": "qoNf16wu0pQ",
      "regular": "https://images.unsplash.com/photo-1774438533054-5a0cc8d24586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1774438533054-5a0cc8d24586?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A woman wearing a traditional orange and yellow sari"
    },
    {
      "id": "yV9rKcXhYX4",
      "regular": "https://images.unsplash.com/photo-1741374240318-99b30b2e2604?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
      "small": "https://images.unsplash.com/photo-1741374240318-99b30b2e2604?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjB3b21hbiUyMHBvcnRyYWl0fGVufDB8Mnx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
      "alt": "A woman poses in a stylish black and white photo."
    }
  ]
};

export const scenePhotos: StockPhoto[] = [
  {
    "id": "OzyvCE9a60M",
    "regular": "https://images.unsplash.com/photo-1764286954620-28029fbae9b6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1764286954620-28029fbae9b6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A bride and groom in traditional indian wedding attire."
  },
  {
    "id": "2KgBh8eTko4",
    "regular": "https://images.unsplash.com/photo-1769500807623-8cca7405512c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1769500807623-8cca7405512c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A bride and groom in traditional wedding attire"
  },
  {
    "id": "Zkl8SLl-gVU",
    "regular": "https://images.unsplash.com/photo-1769500810084-d2667c77a684?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1769500810084-d2667c77a684?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Bride and groom holding hands in traditional wedding attire."
  },
  {
    "id": "W0lNw8WEouM",
    "regular": "https://images.unsplash.com/photo-1781154109545-7a75cd1b3d9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1781154109545-7a75cd1b3d9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Happy couple exchanges yellow flower garlands outdoors."
  },
  {
    "id": "eDa5X0G3o4k",
    "regular": "https://images.unsplash.com/photo-1774019410563-0f38d38af881?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1774019410563-0f38d38af881?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A couple signing documents at a ceremony"
  },
  {
    "id": "ffPQkc7T5qM",
    "regular": "https://images.unsplash.com/photo-1762708547916-ac8d2f3af1fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1762708547916-ac8d2f3af1fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "People dancing at a lively event with blurred motion"
  },
  {
    "id": "N1KLW-J5IsY",
    "regular": "https://images.unsplash.com/photo-1771992230867-6478af331c26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1771992230867-6478af331c26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Couple holding hands with henna and marigold flowers."
  },
  {
    "id": "VcGC9vz_PR0",
    "regular": "https://images.unsplash.com/photo-1774019411246-c3bd5327a160?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1774019411246-c3bd5327a160?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Woman applying intricate henna design on arm"
  },
  {
    "id": "zSX9_MM_pSA",
    "regular": "https://images.unsplash.com/photo-1686865604150-43f95d61416c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1686865604150-43f95d61416c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxzb3V0aCUyMGluZGlhbiUyMHdlZGRpbmclMjBjb3VwbGV8ZW58MHwwfHx8MTc4MzY5NDMzMnww&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "a close up of a woman's hands with hennap"
  },
  {
    "id": "3Dj4SNHu28c",
    "regular": "https://images.unsplash.com/photo-1768341395921-93a8444e007e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1768341395921-93a8444e007e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Hands tying a sacred thread during a traditional ceremony."
  },
  {
    "id": "IWxkqVzOY-0",
    "regular": "https://images.unsplash.com/photo-1774024872335-693ba4dd876f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1774024872335-693ba4dd876f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMXx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Bride places ring on groom's finger during wedding ceremony"
  },
  {
    "id": "rksO8uNkRrI",
    "regular": "https://images.unsplash.com/photo-1771654104630-e3aeb6c15793?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1771654104630-e3aeb6c15793?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMnx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Woman in a colorful sari adjusting her hair outdoors."
  },
  {
    "id": "uhM6J7rvcCs",
    "regular": "https://images.unsplash.com/photo-1768341395956-fed92f537228?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1768341395956-fed92f537228?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxM3x8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Woman wearing traditional indian gold jewelry and red saree"
  },
  {
    "id": "X1AXwfndxxs",
    "regular": "https://images.unsplash.com/photo-1774019410616-2b38e4eeabd2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1774019410616-2b38e4eeabd2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNHx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Applying henna design to a hand with a cone"
  },
  {
    "id": "qkp_i_yNUzk",
    "regular": "https://images.unsplash.com/photo-1779475546066-742c9a580de1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1779475546066-742c9a580de1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxNXx8c291dGglMjBpbmRpYW4lMjB3ZWRkaW5nJTIwY291cGxlfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "Smiling indian woman in traditional attire and jewelry."
  },
  {
    "id": "VJP7K4uihUA",
    "regular": "https://images.unsplash.com/photo-1727430201245-fb796167e302?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1727430201245-fb796167e302?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A couple of people that are hugging each other"
  },
  {
    "id": "MDsZXdTp_Kw",
    "regular": "https://images.unsplash.com/photo-1727430334140-c21dc3d415f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1727430334140-c21dc3d415f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwyfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A man and woman sitting in the back of a car"
  },
  {
    "id": "xwiS7qkkji4",
    "regular": "https://images.unsplash.com/photo-1727430312557-621bfbc592ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1727430312557-621bfbc592ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwzfHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A couple of people that are standing in the dirt"
  },
  {
    "id": "aodC5OimCvo",
    "regular": "https://images.unsplash.com/photo-1727430285085-1d6598cec803?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1727430285085-1d6598cec803?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw0fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A man holding a woman in his arms"
  },
  {
    "id": "X61_Ypmb4ug",
    "regular": "https://images.unsplash.com/photo-1647541736428-f6b48d5bf4a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1647541736428-f6b48d5bf4a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw1fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "a man standing next to a float with a man in a mask on it"
  },
  {
    "id": "SiMzEeMrX2E",
    "regular": "https://images.unsplash.com/photo-1619402259119-9a15d30d5b03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1619402259119-9a15d30d5b03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw2fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "man in white dress shirt kissing woman in red and white floral dress"
  },
  {
    "id": "o3lLS-1e5VY",
    "regular": "https://images.unsplash.com/photo-1641666016347-6aace56c2278?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1641666016347-6aace56c2278?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw3fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "a group of men standing next to each other"
  },
  {
    "id": "vANQ6Qh1O70",
    "regular": "https://images.unsplash.com/photo-1726431531765-7e44461757a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1726431531765-7e44461757a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw4fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "A woman in a yellow dress standing in front of a building"
  },
  {
    "id": "4wev6H3JxGc",
    "regular": "https://images.unsplash.com/photo-1641666017539-7ef651aecbcf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1641666017539-7ef651aecbcf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHw5fHxrZXJhbGElMjBicmlkZSUyMGdyb29tfGVufDB8MHx8fDE3ODM2OTQzMzJ8MA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "a group of men standing around each other"
  },
  {
    "id": "pfrjk53f_3g",
    "regular": "https://images.unsplash.com/photo-1641666017082-02c741e2af4b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8a2VyYWxhJTIwYnJpZGUlMjBncm9vbXxlbnwwfDB8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    "small": "https://images.unsplash.com/photo-1641666017082-02c741e2af4b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5OTYyNzF8MHwxfHNlYXJjaHwxMHx8a2VyYWxhJTIwYnJpZGUlMjBncm9vbXxlbnwwfDB8fHwxNzgzNjk0MzMyfDA&ixlib=rb-4.1.0&q=80&w=400",
    "alt": "a group of men standing next to each other"
  }
];
